### ISSUE TITLE
Suggestion to rename YesN't Interpreter to Red Interpreter

### ISSUE THREAD

**Issue by alibutt30** [Stone-Red-Code/YesNt-Interpreter#1]
The current name of the YesN't interpreter is not only hard to pronounce, it lacks the catchiness too. 

The suggestion is to therefore rename it to a more catchy word like Red interpreter.

**Comment by Stone-Red-Code** [comment]
Closed because of the like/dislike ratio.
Seems like the community doesn't like this name.
